#!/usr/bin/env bash
set -euo pipefail

# =========================================================================
# Boojy Suite status / progress tracker generator
#
# Regenerates the auto SNAPSHOT block in the suite tracker by scanning each
# repo's git + version. The tracker lives in the VAULT (cross-project docs),
# while this script lives in the boojy repo (it's code).
#
#   ./scripts/suite-status.sh                 # writes to the default vault path
#   ./scripts/suite-status.sh /path/to/doc.md # override the output location
#   SUITE_STATUS_DOC=/path/to/doc.md ./scripts/suite-status.sh
#
# Only the block between AUTO:START / AUTO:END is rewritten — the hand-kept
# "Current Milestone" checklist and per-app "Focus" sections are preserved. If
# the doc doesn't exist, it's created from a template with those seeded.
# =========================================================================

cd "$(dirname "$0")/.."                 # repo root (Boojy/) — so sibling paths resolve
DEFAULT_DOC="$HOME/Documents/Vault/Boojy/SUITE_STATUS.md"
DOC="${1:-${SUITE_STATUS_DOC:-$DEFAULT_DOC}}"
START="<!-- SUITE-STATUS:AUTO:START -->"
END="<!-- SUITE-STATUS:AUTO:END -->"

# name | path (relative to this repo root). "." is this repo (the website).
REPOS=(
  "boojy.org (website)|."
  "Boojy Audio (DAW)|../boojy-audio"
  "Boojy Design|../boojy-design"
  "Boojy Notes|../boojy-notes"
  "Boojy Cloud|../boojy-cloud"
)

get_version() {
  local p="$1" v
  if [ -f "$p/package.json" ]; then
    v=$(jq -r '.version // empty' "$p/package.json" 2>/dev/null || true)
    [ -n "$v" ] && { echo "$v"; return; }
  fi
  if [ -f "$p/website/package.json" ]; then
    v=$(jq -r '.version // empty' "$p/website/package.json" 2>/dev/null || true)
    [ -n "$v" ] && { echo "$v"; return; }
  fi
  if [ -f "$p/CHANGELOG.md" ]; then
    v=$(grep -m1 -E '^##[[:space:]]+v?[0-9]' "$p/CHANGELOG.md" | sed -E 's/^##[[:space:]]+//; s/[[:space:]].*$//' || true)
    [ -n "$v" ] && { echo "$v"; return; }
  fi
  echo "—"
}

gen_rows() {
  local entry name path ver branch last d30 dirty
  for entry in "${REPOS[@]}"; do
    name="${entry%%|*}"; path="${entry##*|}"
    if [ ! -d "$path/.git" ]; then
      printf '| %s | _not found_ | — | — | — | — |\n' "$name"
      continue
    fi
    ver=$(get_version "$path")
    branch=$(git -C "$path" branch --show-current 2>/dev/null || echo '—')
    last=$(git -C "$path" log -1 --format='%cd · %s' --date=short 2>/dev/null | cut -c1-58 || echo '—')
    d30=$(git -C "$path" log --since='30 days ago' --oneline 2>/dev/null | wc -l | tr -d ' ')
    dirty=$(git -C "$path" status --porcelain 2>/dev/null | wc -l | tr -d ' ')
    if [ "$dirty" = "0" ]; then dirty="clean"; else dirty="${dirty} uncommitted"; fi
    printf '| %s | %s | %s | %s | %s | %s |\n' "$name" "$ver" "$branch" "$last" "$d30" "$dirty"
  done
}

TODAY=$(date +%Y-%m-%d)
BLOCK_FILE=$(mktemp)
{
  echo "$START"
  echo "_Auto-generated by \`boojy-web/scripts/suite-status.sh\` on ${TODAY} — don't hand-edit this block; re-run the script._"
  echo
  echo "| App | Version | Branch | Last commit | Commits (30d) | Working tree |"
  echo "|-----|---------|--------|-------------|---------------|--------------|"
  gen_rows
  echo "$END"
} > "$BLOCK_FILE"

# Create the tracker from a template (with seeded human sections) if missing.
if [ ! -f "$DOC" ]; then
  mkdir -p "$(dirname "$DOC")"
  cat > "$DOC" << 'TEMPLATE'
# Boojy Suite — Status & Progress Tracker

> The single home for suite-wide progress. Three parts: an auto **Snapshot** (regenerated by
> `boojy-web/scripts/suite-status.sh`), the **Current Milestone** checklist (hand-kept — this is the
> plan; work it top-down), and per-app **Focus** notes. Strategy/intent lives in
> *Boojy Suite — Vision (2026 Refresh)*; this is operational state, not strategy.

## Snapshot

<!-- SUITE-STATUS:AUTO:START -->
<!-- SUITE-STATUS:AUTO:END -->

## Current Milestone — Suite Stabilization & Tooling Consistency

**No new features.** Done when every repo is at a stable, shippable point with its in-flight refactor
closed, *and* every repo has the same maintained `.claude` baseline (CLAUDE.md + dreams.md + hooks +
ledger + session-metrics skill) adapted to its stack. Work the list top-down.

### 1. Finish boojy.org (closest to done — do first)
- [ ] Commit the `astro-migration` branch work
- [ ] Merge → `master` **+ flip CF Pages build settings in lockstep** (deploy trap)
- [ ] Deferred Biome pass (its own commit)

### 2. Tooling baseline consistency (CLAUDE.md + dreams.md + hooks + ledger + session-metrics)
- [x] boojy.org
- [x] boojy-notes
- [x] boojy-design
- [ ] Boojy Audio — add `dreams.md` + post-edit hook + ledger (has CLAUDE.md + a skill already)
- [ ] boojy-cloud — add a minimal baseline (low priority)

### 3. Close in-flight refactors → stable
- [ ] Boojy Design — engine stateful-tail / `CanvasStage` split (see its own `dreams.md`)
- [ ] Boojy Notes — drive to a tagged stable release
- [ ] Boojy Audio — pick a v0.3.x stability cut
- [ ] Boojy Cloud — leave dormant (low priority); no action beyond the baseline above

## Focus — per app (hand-maintained)

> The Snapshot gives the facts; this gives the judgment. Update as priorities move.

### Boojy Audio (DAW) — **active dev, highest priority**
- Now: developing the v0.3.x line.
- Next: pick a stability cut for a clean v0.3.x release.
- Blockers: _none noted._

### Boojy Design — **MVP complete**
- Now: stable at MVP.
- Next: the engine stateful-tail / `CanvasStage` refactor, then scope the animation feature.
- Blockers: _none noted._

### Boojy Notes — **in progress**
- Now: polishing toward a stable release.
- Next: tag a stable release.
- Blockers: _none noted._

### boojy.org (website) — **Astro migration built, pending merge**
- Now: migration complete on `astro-migration`; pending merge to `master`.
- Next: merge + flip CF Pages build settings in lockstep, then the Biome pass.
- Blockers: _none noted._

### Boojy Cloud — **backlog, low priority**
- Now: dormant (Supabase only).
- Next: stand up properly when an app needs production sync beyond Notes' current setup.
- Blockers: _none noted._
TEMPLATE
fi

# Replace the region between the markers with the freshly generated snapshot.
TMP=$(mktemp)
awk -v s="$START" -v e="$END" -v bf="$BLOCK_FILE" '
  index($0, s) { while ((getline line < bf) > 0) print line; close(bf); skip=1; next }
  index($0, e) { skip=0; next }
  !skip { print }
' "$DOC" > "$TMP" && cat "$TMP" > "$DOC"
rm -f "$TMP" "$BLOCK_FILE"

echo "✅ Updated $DOC"
